### PR TITLE
Add ohai attribute support (automatic attrs)

### PR DESCRIPTION
**Pull request by patcon**
This is great! thanks! But would be great to add this suggestion from the comments:
http://jakshi.com/blog/2014/05/12/accessing-chef-attributes-in-serverspec-tests/#comment-1751048684

I'll test it out and submit a PR :)

### CODE REVIEW

**Comment by rexut** [comment]
Hi patcom, did you test it out in real chef environment? I can't but would merge. It looks like a minor change.

**Comment by patcon** [comment]
Yep, using it myself in a chef-zero environment :)

**Comment by patcon** [comment]
Any chance we could get this into a new release? :)

**Comment by rexut** [comment]
see release v1.1.0

**Comment by patcon** [comment]
:+1: thanks!

**Pull request merged**
